# Generated by Django 5.2.5 on 2025-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
