# Generated by Django 5.2.5 on 2025-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0002_alter_debtor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
