# Generated by Django 5.2.5 on 2025-08-07 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0005_alter_debtor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long numbers.', regex='^\\d{10}$')]),
        ),
    ]
