# Generated by Django 5.2.5 on 2025-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0006_alter_debtor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=10),
        ),
    ]
