# Generated by Django 5.2.5 on 2025-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0007_alter_transaction_tran_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_desc',
            field=models.CharField(max_length=200),
        ),
    ]
