# Generated by Django 5.2.5 on 2025-08-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0008_alter_transaction_tran_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
