# Generated by Django 5.2.5 on 2025-08-22 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0009_alter_debtor_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long numbers.', regex='^\\d{10}$')]),
        ),
    ]
