# Generated by Django 5.2.5 on 2025-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0010_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtor',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
