# Generated by Django 5.2.5 on 2025-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0011_debtor_is_admin_debtor_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
